version: '3'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    volumes:
      - sql-volume:/var/opt/mssql
  nosql.data:
    image: mongo
    volumes:
      - nosql-volume:/data/db

  magicsword.core.api:
    image: ${DOCKER_REGISTRY}magicsword.core.api
    build:
      context: ./MagicSword.Core.Api
    depends_on:
      - sql.data

  magicsword.core.logic:
    image: ${DOCKER_REGISTRY}magicsword.core.logic
    build:
      context: ./MagicSword.Core.Logic/ClientApp
    depends_on:
      - nosql.data
      - magicsword.core.api

  magicsword.core.web:
    image: ${DOCKER_REGISTRY}magicsword.core.web
    build:
      context: ./
      dockerfile: MagicSword.Core.Web/ClientApp/Dockerfile
    depends_on:
      - magicsword.core.logic
      
volumes:
  sql-volume:
  nosql-volume: